/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/2d0c6d34-797a-4076-ac97-e148be234e6e 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudColor color_picker;
  bool button_pressed;
  bool motor_enabled;
  bool motor_forward;
  bool switch_forward;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

// ===== Pin assignments =====
const int IN1 = 2;           // Motor direction A
const int IN2 = 3;           // Motor direction B
const int EN1 = 4;           // Motor enable (PWM capable)
const int SWITCH_PIN = 6;    // SPDT switch
const int BUTTON_PIN = 7;    // Stop button

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(200); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();



  // Set the LED as outputs
  pinMode(LED_RED, OUTPUT);
  pinMode(LED_BLUE, OUTPUT);
  pinMode(LED_GREEN, OUTPUT);

  // Motor pins
  pinMode(IN1, OUTPUT);
  pinMode(IN2, OUTPUT);
  pinMode(EN1, OUTPUT);

  // Inputs with internal pull-ups
  pinMode(SWITCH_PIN, INPUT_PULLUP);
  pinMode(BUTTON_PIN, INPUT_PULLUP);

  // Set starting state
  switch_forward = digitalRead(SWITCH_PIN);
  button_pressed = digitalRead(BUTTON_PIN); 
  modifyMotorState(switch_forward, button_pressed);

  Serial.println("System Initialized.");
}

void loop() {
  ArduinoCloud.update();

  // Read inputs
  bool switchState = digitalRead(SWITCH_PIN);
  bool buttonState = digitalRead(BUTTON_PIN); 

  bool stateChanged = false;

  // Detect switch changes
  if (switchState != switch_forward) {
    Serial.print("Switch changed to: ");
    Serial.println(switchState == HIGH ? "FORWARD" : "REVERSE");
    switch_forward = switchState;
    stateChanged = true;
  }

  // Detect button changes
  if (buttonState != button_pressed) {
    Serial.print("Button changed to: ");
    Serial.println(buttonState == HIGH ? "PRESSED" : "RELEASED");
    button_pressed = buttonState;
    stateChanged = true;
  }

  // Only update motor if either input changed
  if (stateChanged) {
    modifyMotorState(switchState, buttonState);
  }

  delay(50); // small delay for stability
}

void modifyMotorState(bool switchState, bool buttonState) {
  if (switchState == HIGH) {
    motor_forward = true;
    // Forward direction — button ignored
    digitalWrite(IN1, HIGH);
    digitalWrite(IN2, LOW);
    analogWrite(EN1, (motor_enabled ? 255 : 0));

  } else {
    motor_forward = false;
    // Reverse direction — check button
    if (buttonState == HIGH) {
      // Stop motor in reverse
      digitalWrite(IN1, LOW);
      digitalWrite(IN2, LOW);
      analogWrite(EN1, (motor_enabled ? 255 : 0));
    } else {
      // Reverse normally
      digitalWrite(IN1, LOW);
      digitalWrite(IN2, HIGH);
      analogWrite(EN1, (motor_enabled ? 255 : 0));
    }
  }
}


void onColorPickerChange() {
  Serial.println("Color changed!");

  // Create a Color object from the cloud variable
  Color currentColor = Color(color_picker.getValue().hue, 
                             color_picker.getValue().sat, 
                             color_picker.getValue().bri);

    // Use the built-in getRGB() method
  uint8_t red, green, blue;
  currentColor.getRGB(red, green, blue);

  Serial.printf("Color Changed to (%d, %d, %d)\n", red, green, blue);

  // Write to pins (ACTIVE-LOW RGB LED)
  analogWrite(LED_RED, 255-red);
  analogWrite(LED_GREEN, 255-green);
  analogWrite(LED_BLUE, 255-blue);
}

/*
  Since MotorForward is READ_WRITE variable, onMotorForwardChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMotorForwardChange()  {
  // Add your code here to act upon MotorForward change
  // if (motor_forward) {
  //   Serial.println("Motor Forwards");
  //   digitalWrite(IN1, HIGH);
  //   digitalWrite(IN2, LOW);
  // } else {
  //   Serial.println("Motor Backwards");
  //   digitalWrite(IN1, LOW);
  //   digitalWrite(IN2, HIGH);
  // }
}

/*
  Since MotorEnabled is READ_WRITE variable, onMotorEnabledChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMotorEnabledChange()  {
  // Add your code here to act upon MotorOn change
  if (motor_enabled) {
    Serial.println("Motor On");
    analogWrite(EN1, 255); // Full speed
    onMotorForwardChange();
  } else {
    Serial.println("Motor Off");
    analogWrite(EN1, LOW); // Stop
  }
}

/*
  Since SwitchForward is READ_WRITE variable, onSwitchForwardChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSwitchForwardChange()  {
  // Add your code here to act upon SwitchForward change
}

/*
  Since ButtonPressed is READ_WRITE variable, onButtonPressedChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onButtonPressedChange()  {
  // Add your code here to act upon ButtonPressed change
}