/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/2d0c6d34-797a-4076-ac97-e148be234e6e 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String active_box;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/
#include <Arduino.h>
#include "Useless_Boxes.h"
#include "thingProperties.h"

// ===== Pin assignments =====
const int IN1 = 2;           // Motor direction A
const int IN2 = 3;           // Motor direction B
const int EN1 = 4;           // Motor enable (PWM capable)
const int LED_R = 5;         // LED Red
const int LED_G = 6;         // LED Green
const int LED_B = 7;         // LED Blue
const int SWITCH_PIN = 8;    // SPDT switch
const int LIMIT_PIN = 9;     // Limit Switch
const int BUTTON_PIN = 10;   // Settings button
const int BUZZER_PIN = 11;   // Buzzer

// === SETTINGS BUTTON HANDLER ======================================
// Adjustable thresholds
const unsigned long LONG_PRESS_TIME = 1000;   // ms
const unsigned long DEBOUNCE_TIME   = 50;     // ms

// === MENU SYSTEM VARIABLES ===
int menuIndex = 0;
const int totalMenus = 3;
bool inSubMenu = false;

// SETTINGS
bool motorAutoMode = false;
int led_brightness_percentage = 100; // 0–100

// Variables for button tracking
bool settingsButtonState = HIGH;
bool lastSettingsButtonState = HIGH;

unsigned long pressedTime = 0;
unsigned long releasedTime = 0;

bool longPressActive = false;
unsigned long lastDebounceTime = 0;

int shortPressCount = 0;
int longPressCount  = 0;

// Keep track of previous press counts
int lastShortPressCount = 0;
int lastLongPressCount  = 0;

// Inactivity timeout
const unsigned long MENU_TIMEOUT_MS = 5000;
unsigned long lastInteractionTime = 0;  // resets every button press

bool led_on = false;

// === MOTOR CONTROL HANDLER ========================================
unsigned long lastMotorUpdate = 0;
const unsigned long MOTOR_UPDATE_INTERVAL = 50; // ms

bool switch_forward = true;
bool button_pressed = false;
bool motor_forward = true;
bool motor_enabled = true;

// ==================================================================
// === SETUP ========================================================
// ==================================================================
void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(200); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();



  // Set the LED as outputs
  pinMode(LED_RED, OUTPUT);
  pinMode(LED_BLUE, OUTPUT);
  pinMode(LED_GREEN, OUTPUT);

  // Motor pins
  pinMode(IN1, OUTPUT);
  pinMode(IN2, OUTPUT);
  pinMode(EN1, OUTPUT);

  // Inputs with internal pull-ups
  pinMode(SWITCH_PIN, INPUT_PULLUP);
  pinMode(LIMIT_PIN, INPUT_PULLUP);

  // Set starting state
  switch_forward = digitalRead(SWITCH_PIN);
  button_pressed = digitalRead(LIMIT_PIN); 
  modifyMotorState(switch_forward, button_pressed);

  // Settings button
  pinMode(BUTTON_PIN, INPUT_PULLUP);

  // Reflect starting state
  onActiveBoxChange();
  Serial.println("System Initialized.");
}

// ==================================================================
// === MAIN LOOP ====================================================
// ==================================================================
void loop() {
    ArduinoCloud.update();
    handleSettingsButton();   // independent from motor
  
    // Run motor control every 50 ms (non-blocking)
    if (millis() - lastMotorUpdate >= MOTOR_UPDATE_INTERVAL) {
      lastMotorUpdate = millis();
      handleMotorControl();
    }

    handleSerialMenu();
}

// ==================================================================
// === SETTINGS BUTTON HANDLER ======================================
// ==================================================================
void handleSettingsButton() {
  bool reading = digitalRead(BUTTON_PIN);

  // Debounce
  if (reading != lastSettingsButtonState) {
    lastDebounceTime = millis();
  }

  if ((millis() - lastDebounceTime) > DEBOUNCE_TIME) {
    if (reading != settingsButtonState) {
      settingsButtonState = reading;

      // Just pressed
      if (settingsButtonState == LOW) {
        pressedTime = millis();
        longPressActive = false;
      }

      // Just released
      else {
        unsigned long pressDuration = millis() - pressedTime;
        if (pressDuration < LONG_PRESS_TIME && !longPressActive) {
          shortPressCount++;
          Serial.print("Short press #");
          Serial.println(shortPressCount);
        }
      }
    }
  }

  // Detect long press
  if (settingsButtonState == LOW && !longPressActive && 
      (millis() - pressedTime > LONG_PRESS_TIME)) {
    longPressActive = true;
    longPressCount++;
    Serial.print("Long press #");
    Serial.println(longPressCount);
  }

  lastSettingsButtonState = reading;
}

// ==================================================================
// === SETTINGS MENU FUNCTIONS ======================================
// ==================================================================
void handleSerialMenu() {
  unsigned long now = millis();

  // Reset to main menu if inactive too long
  if ((now - lastInteractionTime) > MENU_TIMEOUT_MS && (menuIndex != 0 || inSubMenu)) {
    Serial.println("\n⏱️ Menu timed out — returning to main screen.\n");
    menuIndex = 0;
    inSubMenu = false;
    showMenu();
  }
  
  // Handle short press → next menu item
  if (shortPressCount > lastShortPressCount) {
    lastShortPressCount = shortPressCount;
    lastInteractionTime = now;  // activity detected

    if (!inSubMenu) {
      menuIndex = (menuIndex + 1) % totalMenus;
      showMenu();
    } else {
      adjustSubMenu();
    }
  }

  // Handle long press → enter/confirm
  if (longPressCount > lastLongPressCount) {
    lastLongPressCount = longPressCount;
    lastInteractionTime = now;  // activity detected

    if (!inSubMenu) {
      inSubMenu = true;
      enterSubMenu();
    } else {
      inSubMenu = false;
      Serial.println("✅ Saved and returned to main menu.");
      showMenu();
    }
  }
}

// --- MENU DISPLAY ---
void showMenu() {
  Serial.println();
  Serial.print("> Setting ");
  Serial.print(menuIndex + 1);
  Serial.print(": ");

  switch (menuIndex) {
    case 0: Serial.println("Motor Mode"); break;
    case 1: Serial.println("LED Brightness"); break;
    case 2: Serial.println("Active Box"); break;
  }
}

// --- ENTER SUBMENU ---
void enterSubMenu() {
  Serial.print("⚙️ Editing ");
  switch (menuIndex) {
    case 0: Serial.println("Motor Mode"); showMotorMode(); break;
    case 1: Serial.println("LED Brightness"); showBrightness(); break;
    case 2: Serial.println("Active Box"); showActiveBox(); break;
  }
}

// --- ADJUST VALUE ON SHORT PRESS ---
void adjustSubMenu() {
  switch (menuIndex) {
    case 0:
      motorAutoMode = !motorAutoMode;
      showMotorMode();
      break;

    case 1:
      led_brightness_percentage += 10;
      if (led_brightness_percentage > 100) led_brightness_percentage = 0;
      showBrightness();
      adjustLED();
      break;

    case 2:
      setActiveBox(active_box == "TREVOR" ? "MICHAEL" : "TREVOR");
      showActiveBox();
      break;
  }
}

// --- DISPLAY HELPERS ---
void showMotorMode() {
  Serial.print("Motor Mode: ");
  Serial.println(motorAutoMode ? "AUTO" : "MANUAL");
}

void showBrightness() {
  Serial.print("LED Brightness: ");
  Serial.print(led_brightness_percentage);
  Serial.println("%");
}

void showActiveBox() {
  Serial.print("Active Box: ");
  Serial.println(active_box);
}









// ==================================================================
// === MOTOR CONTROL HANDLER ========================================
// ==================================================================
void handleMotorControl() {
  bool switchState = digitalRead(SWITCH_PIN);
  bool buttonState = digitalRead(LIMIT_PIN); // same physical button or another?

  bool stateChanged = false;

  if (switchState != switch_forward) {
    Serial.print("Switch changed to: ");
    Serial.println(switchState == HIGH ? "FORWARD" : "REVERSE");
    switch_forward = switchState;
    stateChanged = true;
  }

  if (buttonState != button_pressed) {
    Serial.print("Button changed to: ");
    Serial.println(buttonState == LOW ? "PRESSED" : "RELEASED");
    button_pressed = buttonState;
    stateChanged = true;
  }

  if (stateChanged) {
    modifyMotorState(switchState, buttonState);
  }
}

// ==================================================================
// === MOTOR BEHAVIOR ===============================================
// ==================================================================
void modifyMotorState(bool switchState, bool buttonState) {
  if (switchState == HIGH) {
    motor_forward = true;
    // Forward direction — button ignored
    digitalWrite(IN1, HIGH);
    digitalWrite(IN2, LOW);
    analogWrite(EN1, (motor_enabled ? 255 : 0));

  } else {
    motor_forward = false;
    // Reverse direction — check button
    if (buttonState == HIGH) {
      // Stop motor in reverse
      digitalWrite(IN1, LOW);
      digitalWrite(IN2, LOW);
      analogWrite(EN1, (motor_enabled ? 255 : 0));
    } else {
      // Reverse normally
      digitalWrite(IN1, LOW);
      digitalWrite(IN2, HIGH);
      analogWrite(EN1, (motor_enabled ? 255 : 0));
    }
  }
}


// ==================================================================
// === LED CONTROL ==================================================
// ==================================================================
void adjustLED() {
  if (led_on) {
    analogWrite(LED_RED, 255-255*led_brightness_percentage/100);
    analogWrite(LED_GREEN, 255-255*led_brightness_percentage/100);
    analogWrite(LED_BLUE, 255-255*led_brightness_percentage/100);
  } else {
    analogWrite(LED_RED,  255-0);
    analogWrite(LED_GREEN, 255-0);
    analogWrite(LED_BLUE, 255-0);
  }
}

void setActiveBox(String box) {
  active_box = box;
  onActiveBoxChange();
}

/*
  Since ActiveBox is READ_WRITE variable, onActiveBoxChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onActiveBoxChange()  {
  Serial.print("Active Box Changed to: ");
  Serial.println(active_box);
  // Add your code here to act upon ActiveBox change
  if (active_box == BOX_NAME) {
    Serial.println("Lighting LED");
    led_on = true;
    adjustLED();
  } else {
    Serial.println("LED OFF");
    led_on = false;
    adjustLED();
  }
}