/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/2d0c6d34-797a-4076-ac97-e148be234e6e 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String active_box;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/
#include <Arduino.h>
#include "Useless_Boxes.h"
#include "thingProperties.h"

// ===== Pin assignments =====
const int EN1 = 2;           // Motor enable (PWM capable)
const int IN1 = 3;           // Motor direction A
const int IN2 = 4;           // Motor direction B
const int RGB_R = 7;         // LED Red
const int RGB_G = 5;         // LED Green
const int RGB_B = 6;         // LED Blue
const int SWITCH_PIN = 8;    // SPDT switch
const int LIMIT_PIN = 9;     // Limit Switch
const int BUTTON_PIN = 10;   // Settings button
const int BUZZER_PIN = 11;   // Buzzer

// === SETTINGS BUTTON HANDLER ======================================
int menuIndex = 0;
bool inSubMenu = false;

// Adjustable thresholds
const unsigned long LONG_PRESS_TIME = 1000;   // ms
const unsigned long DEBOUNCE_TIME   = 50;     // ms

// SETTINGS
bool motorAutoMode = false;
int led_brightness_percentage = 0;

// Variables for button tracking
bool settingsButtonState = HIGH;
bool lastSettingsButtonState = HIGH;

unsigned long pressedTime = 0;
unsigned long releasedTime = 0;

bool longPressActive = false;
unsigned long lastDebounceTime = 0;

int shortPressCount = 0;
int longPressCount  = 0;

// Keep track of previous press counts
int lastShortPressCount = 0;
int lastLongPressCount  = 0;

// Inactivity timeout
const unsigned long MENU_TIMEOUT_MS = 30000;
unsigned long lastInteractionTime = 0;  // resets every button press

bool led_on = false;

// === MOTOR CONTROL HANDLER ========================================
unsigned long lastMotorUpdate = 0;
const unsigned long MOTOR_UPDATE_INTERVAL = 50; // ms

bool switch_forward = true;
bool button_pressed = false;
bool motor_forward = true;
bool motor_enabled = true;

// ==================================================================
// === SETUP ========================================================
// ==================================================================
void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(200); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();



  // Set the Board LED as outputs
  pinMode(LED_RED, OUTPUT);
  pinMode(LED_BLUE, OUTPUT);
  pinMode(LED_GREEN, OUTPUT);

  // Set the RGB LED as outputs
  pinMode(RGB_R, OUTPUT);
  pinMode(RGB_B, OUTPUT);
  pinMode(RGB_G, OUTPUT);
  // Turn LED fully off at startup
  setRGB(0, 0, 0);

  // Set the Buzzer Pin as an output
  pinMode(BUZZER_PIN, OUTPUT);

  // Motor pins
  pinMode(IN1, OUTPUT);
  pinMode(IN2, OUTPUT);
  pinMode(EN1, OUTPUT);

  // Inputs with internal pull-ups
  pinMode(SWITCH_PIN, INPUT_PULLUP);
  pinMode(LIMIT_PIN, INPUT_PULLUP);

  // Set starting state
  switch_forward = digitalRead(SWITCH_PIN);
  button_pressed = digitalRead(LIMIT_PIN); 
  modifyMotorState(switch_forward, button_pressed);

  // Settings button
  pinMode(BUTTON_PIN, INPUT_PULLUP);

  // Reflect starting state
  onActiveBoxChange();
  Serial.println("System Initialized.");
  showMenu();
}

// ==================================================================
// === MAIN LOOP ====================================================
// ==================================================================
void loop() {
    ArduinoCloud.update();
    handleSettingsButton();   // independent from motor
  
    // Run motor control every 50 ms (non-blocking)
    if (millis() - lastMotorUpdate >= MOTOR_UPDATE_INTERVAL) {
      lastMotorUpdate = millis();
      handleMotorControl();
    }

    updateAnimations();   // RGB effects (rainbow, pulse, etc)
    updateBuzzerAlarm();  // Looping buzzer patterns
    handleSerialMenu();
}

// ==================================================================
// === SETTINGS BUTTON HANDLER ======================================
// ==================================================================
void handleSettingsButton() {
  bool reading = digitalRead(BUTTON_PIN);

  // Debounce
  if (reading != lastSettingsButtonState) {
    lastDebounceTime = millis();
  }

  if ((millis() - lastDebounceTime) > DEBOUNCE_TIME) {
    if (reading != settingsButtonState) {
      settingsButtonState = reading;

      // Just pressed
      if (settingsButtonState == LOW) {
        pressedTime = millis();
        longPressActive = false;
      }

      // Just released
      else {
        unsigned long pressDuration = millis() - pressedTime;
        if (pressDuration < LONG_PRESS_TIME && !longPressActive) {
          shortPressCount++;
          //Serial.print("Short press #");
          //Serial.println(shortPressCount);
        }
      }
    }
  }

  // Detect long press
  if (settingsButtonState == LOW && !longPressActive && 
      (millis() - pressedTime > LONG_PRESS_TIME)) {
    longPressActive = true;
    longPressCount++;
    //Serial.print("Long press #");
    //Serial.println(longPressCount);
  }

  lastSettingsButtonState = reading;
}


// ==================================================================
// === SETTINGS MENU (Refactored / Data-Driven) ======================
// ==================================================================

/*
 This system is fully modular:
  - To add a new menu, create:
      showX(), adjustX(), enterX()
  - Then add one line inside the menuItems[] table below.

 Core logic stays unchanged forever.
*/

// Forward declarations for menu handler functions



// =============================================================
// MENU STRUCTURE
// =============================================================



// =============================================================
// MENU TABLE — ADD NEW MENUS HERE
// =============================================================

MenuItem menuItems[] = { 
  { "Motor Mode",      showMotorMode,      adjustMotorMode,      confirmMotorMode },
  { "LED Brightness",  showBrightness,     adjustBrightness,     confirmBrightness },
  { "Active Box",      showActiveBox,      adjustActiveBox,      confirmActiveBox },
  { "RGB LED",         showRGB,            adjustRGB,            confirmRGB },
  { "Buzzer Pattern",  showBuzzer,         adjustBuzzer,         confirmBuzzer }
};

int totalMenus = sizeof(menuItems) / sizeof(MenuItem);


// =============================================================
//     MAIN MENU HANDLER (Button-driven navigation)
// =============================================================

void handleSerialMenu() {
  unsigned long now = millis();

  // Timeout → return to main screen
  if ((now - lastInteractionTime) > MENU_TIMEOUT_MS && (menuIndex != 0 || inSubMenu)) {
    Serial.println("\n⏱️ Menu timed out — returning to main screen.\n");
    menuIndex = 0;
    inSubMenu = false;
    showMenu();
  }

  // Short press: next menu item OR adjust submenu value
  if (shortPressCount > lastShortPressCount) {
    lastShortPressCount = shortPressCount;
    lastInteractionTime = now;

    if (!inSubMenu) {
      menuIndex = (menuIndex + 1) % totalMenus;
      showMenu();
    } else {
      menuItems[menuIndex].onAdjust();
    }
  }

  // Long press: enter submenu OR confirm/save
  if (longPressCount > lastLongPressCount) {
    lastLongPressCount = longPressCount;
    lastInteractionTime = now;

    if (!inSubMenu) {
      inSubMenu = true;
      Serial.print("⚙️ Editing ");
      Serial.println(menuItems[menuIndex].name);
      menuItems[menuIndex].onShow();
    } else {
      inSubMenu = false;
      menuItems[menuIndex].onConfirm();
      Serial.println("✅ Saved and returned to main menu.");
      showMenu();
    }
  }
}


// =============================================================
//    MENU DISPLAY
// =============================================================
void showMenu() {
  Serial.println();
  Serial.print("> Setting ");
  Serial.print(menuIndex + 1);
  Serial.print(": ");
  Serial.println(menuItems[menuIndex].name);

  // Optional: live preview under each menu
  if (menuItems[menuIndex].onShow) {
    menuItems[menuIndex].onShow();
  }
}


// ==================================================================
// === INDIVIDUAL MENU HANDLERS ======================================
// ==================================================================

// ---------------- MOTOR MODE ----------------
void showMotorMode() {
  Serial.print("Motor Mode: ");
  Serial.println(motorAutoMode ? "AUTO" : "MANUAL");
}
void adjustMotorMode() {
  motorAutoMode = !motorAutoMode;
  showMotorMode();
}
void confirmMotorMode() {
  showMotorMode();
}


// ---------------- LED BRIGHTNESS ----------------
void showBrightness() {
  Serial.print("LED Brightness: ");
  Serial.print(led_brightness_percentage);
  Serial.println("%");
}
void adjustBrightness() {
  led_brightness_percentage += 10;
  if (led_brightness_percentage > 100) led_brightness_percentage = 0;

  adjustLED();
  showBrightness();
}
void confirmBrightness() {
  showBrightness();
}


// ---------------- ACTIVE BOX ----------------
void showActiveBox() {
  Serial.print("Active Box: ");
  Serial.println(active_box);
}
void adjustActiveBox() {
  setActiveBox(active_box == "TREVOR" ? "MICHAEL" : "TREVOR");
  showActiveBox();
}
void confirmActiveBox() {
  showActiveBox();
}


// ---------------- RGB LED MENU ----------------
void showRGB() {
  Serial.print("RGB Mode: ");
  switch (currentRGBMode) {
    case RGB_OFF:        Serial.println("OFF"); break;
    case RGB_WHITE:      Serial.println("WHITE"); break;
    case RGB_RAINBOW:    Serial.println("RAINBOW"); break;
    case RGB_BREATHING:  Serial.println("BREATHING"); break;
    case RGB_SOLID_RED:  Serial.println("RED"); break;
    case RGB_SOLID_GREEN:Serial.println("GREEN"); break;
    case RGB_SOLID_BLUE: Serial.println("BLUE"); break;
    default:             Serial.println("UNKNOWN"); break;
  }
}

void adjustRGB() {
  currentRGBMode = (RGBMode)((currentRGBMode + 1) % RGB_MODE_COUNT);
  applyRGBMode();   // update immediately for static colors
  showRGB();
}

void confirmRGB() {
  showRGB();
}


// ---------------- BUZZER MENU ----------------
void showBuzzer() {
  Serial.print("Buzzer Pattern: ");
  switch(requestedBuzzerPattern) {
    case BUZZER_OFF:    Serial.println("OFF"); break;
    case BUZZER_SINGLE: Serial.println("SINGLE"); break;
    case BUZZER_CHIRP:  Serial.println("CHIRP"); break;
    case BUZZER_LOOP:   Serial.println("LOOP"); break;
    case BUZZER_SOS:    Serial.println("SOS"); break;
    default:            Serial.println("UNKNOWN"); break;
  }
}

void adjustBuzzer() {
  requestedBuzzerPattern = (requestedBuzzerPattern + 1) % BUZZER_PATTERN_COUNT;
  showBuzzer();
}


void confirmBuzzer() {
  // Confirm selection on long press
  confirmBuzzerPattern();
  showBuzzer();
}
// ==================================================================
// === RGB LED CONTROL ===============================================
// ==================================================================
void setRGB(uint8_t r, uint8_t g, uint8_t b) {
  // Common anode inversion
  analogWrite(RGB_R, 255 - r);
  analogWrite(RGB_G, 255 - g);
  analogWrite(RGB_B, 255 - b);
}

void applyRGBMode() {
  switch (currentRGBMode) {
    case RGB_OFF:
      setRGB(0,0,0);
      break;
    case RGB_WHITE:
      setRGB(255,255,255);
      break;
    case RGB_SOLID_RED:
      setRGB(255,0,0);
      break;
    case RGB_SOLID_GREEN:
      setRGB(0,255,0);
      break;
    case RGB_SOLID_BLUE:
      setRGB(0,0,255);
      break;
    case RGB_RAINBOW:
    case RGB_BREATHING:
      // handled in updateAnimations()
      break;
  }
}

void updateAnimations() {
  unsigned long now = millis();
  
  if (currentRGBMode == RGB_RAINBOW && now - lastRGBAnimation > RGB_UPDATE_INTERVAL) {
    lastRGBAnimation = now;
    int r = (sin((rainbowPos) * 0.05) * 127) + 128;
    int g = (sin((rainbowPos*2) * 0.05) * 127) + 128;
    int b = (sin((rainbowPos*3) * 0.05) * 127) + 128;
    setRGB(r,g,b);
    rainbowPos++;
  }

  if (currentRGBMode == RGB_BREATHING && now - lastRGBAnimation > RGB_UPDATE_INTERVAL) {
    lastRGBAnimation = now;
    breathValue += breathDir * 2; // adjust speed
    if (breathValue >= 250) breathDir = -1;
    if (breathValue <= 5) breathDir = 1;
    setRGB(breathValue, breathValue, breathValue);
  }
}



// ==================================================================
// === BUZZER CONTROL ===============================================
// ==================================================================
void stopBuzzer() {
  activeBuzzerPattern = BUZZER_OFF;
  buzzerStep = 0;
  buzzerState = false;
  noTone(BUZZER_PIN);
}

void confirmBuzzerPattern() {
  // Called when long press confirms selection
  activeBuzzerPattern = requestedBuzzerPattern;
  buzzerStep = 0;
  buzzerState = false;
  buzzerLast = millis();
  noTone(BUZZER_PIN);
}
// Non-blocking update (call inside loop)
void updateBuzzerAlarm() {
  unsigned long now = millis();

  switch (activeBuzzerPattern) {
    case BUZZER_OFF:
      noTone(BUZZER_PIN);
      break;

    case BUZZER_SINGLE:
      if (buzzerStep == 0) {
        tone(BUZZER_PIN, 1000);
        buzzerLast = now;
        buzzerStep = 1;
      } else if (now - buzzerLast >= 120) {
        noTone(BUZZER_PIN);
        activeBuzzerPattern = BUZZER_OFF;
        buzzerStep = 0;
      }
      break;

    case BUZZER_CHIRP: {
      int chirpFreqs[3] = {800, 1200, 800};
      int duration = 120;
      if (buzzerStep < 3) {
        if (now - buzzerLast >= duration + 50 || buzzerStep == 0) {
          tone(BUZZER_PIN, chirpFreqs[buzzerStep]);
          buzzerLast = now;
          buzzerStep++;
        }
      } else if (now - buzzerLast >= duration) {
        noTone(BUZZER_PIN);
        activeBuzzerPattern = BUZZER_OFF;
        buzzerStep = 0;
      }
      break;
    }

    case BUZZER_LOOP:
      if (now - buzzerLast >= BUZZER_INTERVAL) {
        buzzerLast = now;
        buzzerState = !buzzerState;
        if (buzzerState) tone(BUZZER_PIN, 1000);
        else noTone(BUZZER_PIN);
      }
      break;

    case BUZZER_SOS: {
      unsigned int sosDurations[10] = {0,150,150,150,400,400,400,150,150,150};
      if (buzzerStep < 10) {
        if (now - buzzerLast >= sosDurations[buzzerStep] + 150) {
          tone(BUZZER_PIN, 800, sosDurations[buzzerStep]);
          buzzerLast = now;
          buzzerStep++;
        }
      } else if (now - buzzerLast >= 150) {
        activeBuzzerPattern = BUZZER_OFF;
        buzzerStep = 0;
      }
      break;
    }
  }
}



// ==================================================================
// === MOTOR CONTROL HANDLER ========================================
// ==================================================================
void handleMotorControl() {
  bool switchState = digitalRead(SWITCH_PIN);
  bool buttonState = digitalRead(LIMIT_PIN); // same physical button or another?

  bool stateChanged = false;

  if (switchState != switch_forward) {
    Serial.print("Switch changed to: ");
    Serial.println(switchState == HIGH ? "FORWARD" : "REVERSE");
    switch_forward = switchState;
    stateChanged = true;
  }

  if (buttonState != button_pressed) {
    Serial.print("Button changed to: ");
    Serial.println(buttonState == LOW ? "PRESSED" : "RELEASED");
    button_pressed = buttonState;
    stateChanged = true;
  }

  if (stateChanged) {
    modifyMotorState(switchState, buttonState);
  }
}

// ==================================================================
// === MOTOR BEHAVIOR ===============================================
// ==================================================================
void modifyMotorState(bool switchState, bool buttonState) {
  if (switchState == HIGH) {
    motor_forward = true;
    // Forward direction — button ignored
    digitalWrite(IN1, HIGH);
    digitalWrite(IN2, LOW);
    analogWrite(EN1, (motor_enabled ? 255 : 0));

  } else {
    motor_forward = false;
    // Reverse direction — check button
    if (buttonState == HIGH) {
      // Stop motor in reverse
      digitalWrite(IN1, LOW);
      digitalWrite(IN2, LOW);
      analogWrite(EN1, (motor_enabled ? 255 : 0));
    } else {
      // Reverse normally
      digitalWrite(IN1, LOW);
      digitalWrite(IN2, HIGH);
      analogWrite(EN1, (motor_enabled ? 255 : 0));
    }
  }
}


// ==================================================================
// === BOARD LED CONTROL ============================================
// ==================================================================
void adjustLED() {
  if (led_on) {
    analogWrite(LED_RED, 255-255*led_brightness_percentage/100);
    analogWrite(LED_GREEN, 255-255*led_brightness_percentage/100);
    analogWrite(LED_BLUE, 255-255*led_brightness_percentage/100);
  } else {
    analogWrite(LED_RED,  255-0);
    analogWrite(LED_GREEN, 255-0);
    analogWrite(LED_BLUE, 255-0);
  }
}


// ==================================================================
// === ACTIVE BOX SETTER ============================================
// ==================================================================
void setActiveBox(String box) {
  active_box = box;
  onActiveBoxChange();
}

/*
  Since ActiveBox is READ_WRITE variable, onActiveBoxChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onActiveBoxChange()  {
  Serial.print("Active Box Changed to: ");
  Serial.println(active_box);
  // Add your code here to act upon ActiveBox change
  if (active_box == BOX_NAME) {
    Serial.println("Lighting LED");
    led_on = true;
    adjustLED();
  } else {
    Serial.println("LED OFF");
    led_on = false;
    adjustLED();
  }
}