#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/2d0c6d34-797a-4076-ac97-e148be234e6e 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudColor color_picker;
  bool switch_on;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  // set the digital pins as outputs
  pinMode(LED_RED, OUTPUT);
  pinMode(LED_BLUE, OUTPUT);
  pinMode(LED_GREEN, OUTPUT);
}

void loop() {
  ArduinoCloud.update();

  // Read Position of Switch

  // If Switch is moved into UP
  // Trigger Switch 1 Variable to the ON position





}


void onColorPickerChange() {
  Serial.println("Color changed!");

  // Create a Color object from the cloud variable
  Color currentColor = Color(color_picker.getValue().hue, 
                             color_picker.getValue().sat, 
                             color_picker.getValue().bri);

    // Use the built-in getRGB() method
  uint8_t red, green, blue;
  currentColor.getRGB(red, green, blue);

  Serial.printf("RGB = %d, %d, %d\n", red, green, blue);

  // Write to pins (ACTIVE-LOW RGB LED)
  analogWrite(LED_RED, 255-red);
  analogWrite(LED_GREEN, 255-green);
  analogWrite(LED_BLUE, 255-blue);
}

/*
  Since SwitchOn is READ_WRITE variable, onSwitchOnChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSwitchOnChange()  {
  // Add your code here to act upon SwitchOn change
}
