/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/2d0c6d34-797a-4076-ac97-e148be234e6e 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudColor color_picker;
  bool motor_forward;
  bool motor_on;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

/*
Assemble the circuit following the pinout:

Switch common -> +3.3V
Switch throw A -> 1k -> IN1 (10k -> GND)
Switch throw B -> 1k -> IN2 (10k -> GND)

Button C -> +3.3V
Button NO -> 1k -> IN1 (shared node)
Button NO -> BUTTON_PIN (Arduino pin, direct)
Button NO / IN1 -> 10k -> GND

L293D:
  Pin8 (Vcc2) -> +6V
  Pin16 (Vcc1) -> +5V recommended
  Pin1 (EN1) -> D4 (Arduino PWM)
  OUT1 -> Motor A
  OUT2 -> Motor B
GNDs tied: Arduino GND, L293D GNDs, motor supply GND
*/

#include "thingProperties.h"

// Motor pins
const int BUTTON_PIN  = 5;  // Button Pin state read
const int EN1  = 4;  // Enable pin (PWM for speed)
const int IN1_READ_PIN  = 3;  // input 1 state read
const int IN2_READ_PIN  = 2;  // input 2 state read

bool lastIn1 = LOW;
bool lastIn2 = LOW;
bool lastButton = LOW;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  // set the digital pins as outputs
  pinMode(LED_RED, OUTPUT);
  pinMode(LED_BLUE, OUTPUT);
  pinMode(LED_GREEN, OUTPUT);

  // Set motor control pins as outputs
  pinMode(EN1, OUTPUT);
  pinMode(IN1_READ_PIN, INPUT);
  pinMode(IN2_READ_PIN, INPUT);
  pinMode(BUTTON_PIN, INPUT);

  // Start with motor stopped
  digitalWrite(EN1, LOW);
}

void loop() {
  ArduinoCloud.update();

  bool in1 = digitalRead(IN1_READ_PIN);
  bool in2 = digitalRead(IN2_READ_PIN);
  bool button = digitalRead(BUTTON_PIN);

  // --- Detect switch change ---
  if (in1 != lastIn1 || in2 != lastIn2) {
    String direction;
    if (in1 && !in2) direction = "FORWARD";
    else if (!in1 && in2) direction = "REVERSE";
    else if (in1 && in2) direction = "BRAKE (both high)";
    else direction = "COAST (both low)";

    Serial.print("Switch changed → Direction: ");
    Serial.println(direction);

    lastIn1 = in1;
    lastIn2 = in2;
  }

  // --- Detect button change ---
  if (button != lastButton) {
    if (button)
      Serial.println("Stop Button released");
    else
      Serial.println("Stop Button pressed");

    lastButton = button;
  }

  delay(50);  // Small debounce delay
  
}


void onColorPickerChange() {
  Serial.println("Color changed!");

  // Create a Color object from the cloud variable
  Color currentColor = Color(color_picker.getValue().hue, 
                             color_picker.getValue().sat, 
                             color_picker.getValue().bri);

    // Use the built-in getRGB() method
  uint8_t red, green, blue;
  currentColor.getRGB(red, green, blue);

  Serial.printf("Color Changed to (%d, %d, %d)\n", red, green, blue);

  // Write to pins (ACTIVE-LOW RGB LED)
  analogWrite(LED_RED, 255-red);
  analogWrite(LED_GREEN, 255-green);
  analogWrite(LED_BLUE, 255-blue);
}

/*
  Since MotorForward is READ_WRITE variable, onMotorForwardChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMotorForwardChange()  {
  // Add your code here to act upon MotorForward change
  // if (motor_forward) {
  //   Serial.println("Motor Forwards");
  //   digitalWrite(IN1, HIGH);
  //   digitalWrite(IN2, LOW);
  // } else {
  //   Serial.println("Motor Backwards");
  //   digitalWrite(IN1, LOW);
  //   digitalWrite(IN2, HIGH);
  // }
}

/*
  Since MotorOn is READ_WRITE variable, onMotorOnChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMotorOnChange()  {
  // Add your code here to act upon MotorOn change
  if (motor_on) {
    Serial.println("Motor On");
    analogWrite(EN1, 255); // Full speed
    onMotorForwardChange();
  } else {
    Serial.println("Motor Off");
    analogWrite(EN1, LOW); // Stop
  }
}
