// Code generated by Arduino IoT Cloud, DO NOT EDIT.
#include "arduino_secrets_michael.h" // Replace this with your own secrets file
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "550183ea-c36f-4b2c-bdec-60b3023f3c77";

const String BOX_NAME = SECRET_BOX_NAME;

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onActiveBoxChange();

String active_box;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(active_box, READWRITE, ON_CHANGE, onActiveBoxChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
