// Code generated by Arduino IoT Cloud, DO NOT EDIT.
#include "arduino_secrets.h" // wrapper that selects device secrets via build flag
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h> 

const char DEVICE_LOGIN_NAME[]  = SECRET_DEVICE_ID;
const char DEVICE_KEY[]         = SECRET_DEVICE_KEY;    // Secret device password

void onActiveBoxChange();

void onOtaRequestChange();

String ota_url;
String ota_target;

String active_box;

void connectToPreferredWiFi();

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(active_box, READWRITE, ON_CHANGE, onActiveBoxChange);
  ArduinoCloud.addProperty(ota_url, READWRITE, ON_CHANGE, onOtaRequestChange);
  ArduinoCloud.addProperty(ota_target, READWRITE, ON_CHANGE, onOtaRequestChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection;
