// Code generated by Arduino IoT Cloud, DO NOT EDIT.
#include "arduino_secrets.h" // wrapper that selects device secrets via build flag
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h> 

const char DEVICE_LOGIN_NAME[]  = SECRET_DEVICE_ID;

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]         = SECRET_DEVICE_KEY;    // Secret device password

void onActiveBoxChange();

String active_box;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(active_box, READWRITE, ON_CHANGE, onActiveBoxChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
